# Generated by Django 3.1.7 on 2021-03-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0003_auto_20210311_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='author_name',
            new_name='user',
        ),
    ]
