# Generated by Django 3.1.7 on 2021-03-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0004_auto_20210311_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='author_name',
        ),
    ]
