# Generated by Django 3.1.7 on 2021-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.ImageField(upload_to='evidence')),
                ('clue_list', models.CharField(max_length=300)),
                ('num_clues', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
