# Generated by Django 3.1.7 on 2021-05-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='parent_list',
            new_name='parent_clues',
        ),
    ]
