# Generated by Django 3.1.7 on 2021-04-15 16:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='story',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
