# Generated by Django 3.1.7 on 2021-04-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20210415_1216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='story',
            managers=[
            ],
        ),
    ]
