# Generated by Django 3.1.7 on 2021-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20210415_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='num_clues',
        ),
    ]
