# Generated by Django 3.1.7 on 2021-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_story_num_clues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='synopsis',
            field=models.CharField(max_length=500),
        ),
    ]
