# Generated by Django 3.1.7 on 2021-04-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0006_auto_20210415_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='clue_list',
        ),
    ]
